version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - veridian-network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: runner
    ports:
      - "8000:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/veridian.db
    volumes:
      - ./data:/app/data
    devices:
      - /dev/tty.usbmodem1101:/dev/tty.usbmodem1101  # macOS Arduino device
      - /dev/ttyUSB0:/dev/ttyUSB0  # Linux Arduino device (Pi 4)
      - /dev/ttyACM0:/dev/ttyACM0  # Linux Arduino device (Pi 4)
    privileged: true  # Required for serial port access
    restart: unless-stopped
    networks:
      - veridian-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # For SSL certificates
    depends_on:
      - client
      - server
    restart: unless-stopped
    networks:
      - veridian-network

volumes:
  data:
    driver: local

networks:
  veridian-network:
    driver: bridge
