services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      target: development
    volumes:
      - ./client/src:/app/client/src  # Mount source files for hot reload
      - ./client/package.json:/app/client/package.json  # Mount package.json
      - ./client/next.config.js:/app/client/next.config.js  # Next.js config
      - ./client/tailwind.config.ts:/app/client/tailwind.config.ts  # Tailwind config
      - ./client/tsconfig.json:/app/client/tsconfig.json  # TypeScript config
      - ./client/postcss.config.cjs:/app/client/postcss.config.cjs  # PostCSS config
      - ./package.json:/app/package.json  # Root package.json for workspace
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    command: ["npm", "run", "dev", "--workspace=client"]
    depends_on:
      - server
    networks:
      - veridian-network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: development
    volumes:
      - .:/app  # Mount entire workspace for server
      - server_node_modules:/app/node_modules  # Preserve container's node_modules
      - ./data:/app/data
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_PATH=/app/data/veridian.db
    command: ["npm", "run", "dev:mock", "--workspace=server"]
    networks:
      - veridian-network

volumes:
  server_node_modules:
    driver: local
  data:
    driver: local

networks:
  veridian-network:
    driver: bridge
